USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

ALTER DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE
RENAME TO GOOGLE_ANALYTICS;
USE DATABASE GOOGLE_ANALYTICS;
-- A)

SHOW SCHEMAS IN DATABASE GOOGLE_ANALYTICS;

USE SCHEMA GOOGLE_ANALYTICS.DATAFEEDS;
SHOW TABLES IN SCHEMA GOOGLE_ANALYTICS.DATAFEEDS;

-- B)
DESCRIBE TABLE GOOGLE_ANALYTICS.DATAFEEDS.GOOGLE_KEYWORDS;

-- C)
SELECT count(*) AS total_rows
FROM GOOGLE_ANALYTICS.DATAFEEDS.GOOGLE_KEYWORDS;
-- 35046855

-- D)
SELECT MIN(DATE) AS first_search_date,
        MAX(DATE) AS last_search_date
FROM GOOGLE_ANALYTICS.DATAFEEDS.GOOGLE_KEYWORDS;
-- first: 22-06-01, last: 22-06-30

 -- E)
SELECT KEYWORD, COUNT(*) AS total_searches
FROM GOOGLE_ANALYTICS.DATAFEEDS.GOOGLE_KEYWORDS
GROUP BY KEYWORD
ORDER BY total_searches DESC
LIMIT 10;

-- F)
SELECT COUNT(DISTINCT KEYWORD) AS unique_keywords
FROM GOOGLE_ANALYTICS.DATAFEEDS.GOOGLE_KEYWORDS
GROUP BY KEYWORD
ORDER BY unique_keywords DESC
LIMIT 10;
-- 7263686

-- G)

SELECT PLATFORM, COUNT(DISTINCT USER_ID) AS unique_users
FROM GOOGLE_ANALYTICS.DATAFEEDS.GOOGLE_KEYWORDS
GROUP BY PLATFORM
ORDER BY unique_users DESC;